In [1]:
!pip install instaloader
!pip install schedule

Collecting instaloader
  Downloading instaloader-4.8.4.tar.gz (54 kB)
     |████████████████████████████████| 54 kB 2.4 MB/s
Requirement already satisfied: requests>=2.4 in /usr/local/lib/python3.7/dist-packages (from instaloader) (2.23.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.4->instaloader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.4->instaloader) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.4->instaloader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.4->instaloader) (2021.10.8)
Building wheels for collected packages: instaloader
  Building wheel for instaloader (setup.py) ... done
  Created wheel for instaloader: filename=instaloader-4.8.4-py3-none-any.whl size=58802 sha256=ac52c5b7efd2032148b26ba5bdc37b396ca51e45f47668a6ba89762255c8ef44
  Stored in directory: /root/.cache/pip/wheels/57/41/71/b3a2e3ce18841b9db8a955ca7257439aa6bad8a87806b9eb9c
Successfully built instaloader
Installing collected packages: instaloader
Successfully installed instaloader-4.8.4
Collecting schedule
  Downloading schedule-1.1.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: schedule
Successfully installed schedule-1.1.0

In [2]:
from instaloader import Instaloader, Profile
import schedule
import time
from datetime import date, timedelta, datetime
import csv
import pandas as pd

In [3]:
brothers = [
            'dra.laiscaldass',
            'lucianoestevan',
            'notassobrejessi',
            'eusouoeli',
            'eslomarques',
            'bissolilucas',
            'ba.heck',
            'rodrigo.mussi',
            'deonaty_',
            'vyniof',
            'pedroscooby',
            'brunnagoncalves',
            'iampauloandre',
            'arthuraguiar',
            'jadepicon',
            'naiaraazevedo',
            'dsilvaoficial',
            'eumaria',
            'linndaquebrada',
            'tiagoabravanel'
]

In [4]:
# cols = ['periodo', 'perfil', 'seguidores']
# seguidores_bbb = pd.DataFrame(columns = cols)

seguidores_bbb = pd.read_csv('/content/seguidores_bbb.csv')

In [5]:
for b in brothers:
  L = Instaloader()
  profile = Profile.from_username(L.context, b)
  periodo = (datetime.now() - timedelta(hours = 3)).strftime('%Y-%m-%d %H:%M:%S')
  seg = profile.followers
  seguidores_bbb = seguidores_bbb.append({'periodo':periodo, 'perfil':b, 'seguidores':seg}, ignore_index=True)

seguidores_bbb.to_csv('/content/seguidores_bbb.csv', na_rep='', index=False)
#exec("seguidores_bbb.to_csv('/content/seguidores_bbb_{}.csv', na_rep='', index=False)".format(periodo))
seguidores_bbb

                periodo           perfil  seguidores
0   2022-01-16 07:00:08  dra.laiscaldass      441789
1   2022-01-16 07:00:10   lucianoestevan      222541
2   2022-01-16 07:00:12  notassobrejessi      316066
3   2022-01-16 07:00:16        eusouoeli      178358
4   2022-01-16 07:00:20      eslomarques      696065
..                  ...              ...         ...
95  2022-01-18 07:00:51    naiaraazevedo     5564388
96  2022-01-18 07:00:54    dsilvaoficial      735796
97  2022-01-18 07:00:56          eumaria     1456413
98  2022-01-18 07:00:57   linndaquebrada      646862
99  2022-01-18 07:01:03   tiagoabravanel     2618924

[100 rows x 3 columns]